declare module '*.module.css';
declare module '*.module.sass';
declare module '*.module.scss';
declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.bmp'
declare module '*.tiff'
