// Generated by dts-bundle-generator v5.9.0

export declare const add: (a: string, b: string) => string;
export declare class Hello {
	private name;
	constructor(name: string);
}
export default add;

export {};
